import type { Metadata } from "next";
import NextImage from "next/image";
import NextLink from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import { Provider } from "@/components/ui/provider";
import { Box, Flex, HStack, Link as CLink, Text, Container } from "@chakra-ui/react";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const menuItems = [
    { label: "Tutorials", href: "/" },
    { label: "Blog", href: "/blog" },
    { label: "Inspo", href: "/inspo" },
  ];

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Provider>
          <Box as="header" borderBottom="1px solid" borderColor="gray.100">
            <Container maxW="6xl" px={{ base: 4, md: 6 }}>
              <Flex as="nav" aria-label="Main" h="60px" align="center" justify="space-between">
                <NextLink href="/" aria-label="Go to home" passHref legacyBehavior>
                  <CLink _hover={{ textDecoration: "none" }}>
                    <HStack gap={3}>
                      <Box pos="relative" h="40px" w="40px" borderRadius="50%" overflow="hidden">
                        <NextImage
                          src="https://miever.s3.ap-east-1.amazonaws.com/static/nail-art/logo.webp"
                          alt="Nail Art"
                          fill
                          sizes="40px"
                          priority
                          unoptimized
                        />
                      </Box>
                      <Text fontWeight="semibold" display={{ base: "none", md: "block" }}>
                        Nail Art
                      </Text>
                    </HStack>
                  </CLink>
                </NextLink>

                <HStack as="ul" gap={8} listStyleType="none" m={0} display={{ base: "none", md: "flex" }}>
                  {menuItems.map((item) => (
                    <Box as="li" key={item.href}>
                      <NextLink href={item.href} passHref legacyBehavior>
                        <CLink fontSize="lg">{item.label}</CLink>
                      </NextLink>
                    </Box>
                  ))}
                </HStack>

                <NextLink href="/login" passHref legacyBehavior>
                  <CLink fontSize="lg">Login</CLink>
                </NextLink>
              </Flex>
            </Container>
          </Box>

          <Box as="main">
            {children}
          </Box>
        </Provider>
      </body>
    </html>
  );
}
